### ISSUE TITLE
Ended a day with negative money

### ISSUE THREAD

**Issue by ValenberghsSven** [propstg/plateup-overcooked-patience#5]
I added some mods including this one and used the default settings.
I was going to lose a run because of slow eaters + herd mentality so used the creative mod to spawn in stuff to fully automate burgers (I only take orders)

I summoned everyone at once with the booking desk and I lost 1287 coins when the first queue patience bar depleted.
After that the automation could keep up with the table clearing so I ended the day without anymore patience lost.

I was in the green before the end of the day (dunno, at least +100 coins)
But the end results showed I had a balance of -61. (should have taken a picture but didn't...)
So I started the next day with negative money (and failed the restaurant due to the same scenario)

Here is the log file.
[negative_balance.log](https://github.com/propstg/plateup-overcooked-patience/files/10301180/negative_balance.log)

Only have the logs, no screenshots and the save got deleted.
in the logs you can see the final 2 days I used booking tables 4 times in a row.
`Adding 11 for identifier 238041352` x4
Made some money on the first customers
Shortly after I lost -1467 for patience according to the logs. but I remember seeing 1287 pop up on screen tbh.

I started the day with negative money (Unsure how much, I thought around -60)
`Adding 12 for identifier 238041352` x4
Made no money from customers yet and lost because I had -25 money.

I will play around some more and if it happens again I can share the save/logs/screenshots

List of mods:
KitchenLib
Harmony
PlateupPrepGhost
Overcooked Patience
Creative Mode Rebron

**Comment by propstg** [comment]
Amazing details, thank you. <3 I'm not sure how the pop up would be different from the amount in the logs, since I think it's only getting looked up once per event, but I wouldn't be surprised if something weird is going on. I'll take a closer look at this when I have a chance.

Maybe as a stopgap, I can make it set your money to 0 if it is somehow negative at the start of the day? Not ideal, obviously, but maybe better than instantly losing. ':D

**Comment by ValenberghsSven** [comment]
@propstg 
Managed to get another occurence.
Started the day with unknown amount of money (something 100+)
booking desk called
Patience lost -158 (both in logs and what I saw visually)
I ended the day with 85 coins (top left) + looking at logs, 85 seems correct from earnings.
However when the day results were calculated, I lost more 7 coins and ended up with 78.

log
[lost_coins.log](https://github.com/propstg/plateup-overcooked-patience/files/10304614/lost_coins_log.log)
screenshot
![lost_coins_picture](https://user-images.githubusercontent.com/22245223/209578649-d405d7d8-faaa-4c2b-94c9-b96874a953ef.png)
Still have this save game.

Not sure where the 7 coins difference comes from (since the food is always 5 coins)
the numbers in the endresult are correct.

What I am missing from the totals screen is a bonus for amount of players (since I always play solo I see this a lot)
That amount usually gets added in the end result screen.
Could it be that I am getting a hidden bonus for solo play (maybe 24 coins) which is then calculated against the negative balance
So -31 + 24 = -7. so I lose 7 coins?

**Comment by propstg** [comment]
@ValenberghsSven Good catch! I think you're absolutely right about it being the player bonus, after looking at the decompiled game code.

This is roughly how the player bonus is calculated: `Math.ceilToInt((money at end of day - money at start of day) * reward player modifier)`. (for single player, the modifier is 0.25)

It looks like you would've started the day with 116 (earned 42 on the day before losing 158). Totaling the add events, you did earn and finish the day with 85 after that. So you'd get a player bonus of `(85 - 116) * 0.25 = -7.75`, which would become -7 after `ceil`.

The player bonus is applied at the end of the day, as the pop up is created, and is only shown if the bonus is > 0, so if the bonus is negative, it won't get displayed, but it will still be subtracted from your money.

I'm not quite sure what the best way to fix it is. I'm leaning towards trying to just zero out the bonus if it's negative, since I doubt the game was ever intended to handle _losing_ money during a day. Do you have any suggestions?

ETA: I can recreate this issue reliably when intentionally ending the day with less money than I started with.

**Comment by propstg** [comment]
Looks like zeroing out a negative bonus is possible. 
![image](https://user-images.githubusercontent.com/22607691/209751885-a4e01842-f8a0-4d28-83f2-ee6bcd4ef19d.png)

**Comment by ValenberghsSven** [comment]
Nice, glad I could help narrow down the problem.

As to the solution, I've checked the code (I am mainly java / javascript programmer, c# is readable)
The player bonus will not be added if it's negative (If you end the day with less money than you started with).
You should still get the bonus if you have a positive income after losing patience. (start with 0 money, make 5, lose 5, make 60)

Would it make sense that you shouldn't get a player bonus at all if you would have lost the game in vanilla?
Not requesting a change, just floating ideas.

The current fix looks good. Will try it out next time I play.

**Comment by ValenberghsSven** [comment]
Played a few rounds today.
Losing money on purpose with a negative player count bonus does not take away money when showing the results.
Player count bonus is not shown in that case.

👍 Can close this issue I reckon.

**Comment by propstg** [comment]
Awesome, glad it's working for you! Thanks so much for your help and patience!

I'm definitely more comfortable in Java and Javascript, myself. :D I'm happy the solution was readable enough.

I agree that it does make sense to not give a bonus at all if anyone loses patience in a day, and I think that would be fairly simple to add, at this point. I'll go ahead and create an issue, and probably add it next time I'm making changes to this project.
