### ISSUE TITLE
Allow modifying base coin loss for Progressive and Exponential.

### ISSUE THREAD

**Issue by feildmaster** [propstg/plateup-overcooked-patience#9]
Instead of starting at 5, I'd like the ability to chose 5/10 (possibly 15) as the base.

At first I was thinking of making Progressive and Exponential a mode, but then you also have 0 as a coin option, and it seems to be a bit more work than I thought it would entail.

I believe it could add another layer of difficulty to the mod.

**Comment by propstg** [comment]
Hi @feildmaster,

I like this idea, thanks. I think it would work, if Lose Coins' extra features were split out into distinct modes.

Modes might be:
* `Off` (default game functionality)
* `No Patience Penalty` (current 0 coins functionality)
* `Lose Coins - Fixed`
* `Lose Coins - Progressive`
* `Lose Coins - Exponential`
* `Lose Coins - ALL`
* `3 Strikes`

And then change the lose coins option to just be numeric and have it be used for the fixed amount and as the base for progressive/exponential.

This *would* be a bit of work, I think mainly because I would want to try to make sure a user doesn't lose their current settings when they update the mod, but I think it's possible and having explicit modes would maybe be less confusing than having Lose Coins have different functionality depending on what coin value is selected.

**Comment by propstg** [comment]
I think I have the changes detailed above pretty much finished, just need to test more, particularly around transitioning existing settings. I'll probably try to release it sometime this weekend.

Here's a preview:
![image](https://user-images.githubusercontent.com/22607691/210718732-5dfddf3f-02b4-4416-96fd-630326d40f07.png)

**Comment by propstg** [comment]
This has been released on the workshop.

**Comment by feildmaster** [comment]
That's great, thanks for the quick update and release!
